# Generated by Django 3.0 on 2021-03-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210323_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('MI', 'MI'), ('Fitbit', 'Fitbit'), ('Fasttrack', 'Fasttrack'), ('Realme', 'Realme'), ('Fossil', 'Fossil'), ('Amazefit', 'Amazefit'), ('Noise', 'Noise')], max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_disc', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('sellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
